/* ─────────────────────────────────────────────────────────
 * FORMIC CONFIG — the defaults an app chose, read by components
 *
 * Generated by scripts/apply_config.py from formic.config.json.
 * Edit the json (or paste a block from formicai.dev/customize)
 * and run the script; do not edit this file by hand.
 *
 * Only the choices that are prop defaults live here. Colour,
 * palette, radius, size and theme are tokens and <html> data
 * attributes, which the same script writes.
 * ───────────────────────────────────────────────────────── */
export type FormicConfig = {
  /** people without a `src`: initials in a tinted circle, a drawn face
   *  (DiceBear notionists, generated from the name), or a placeholder
   *  photo (pravatar, picked by the name) until real photos exist */
  avatar: "initials" | "doodle" | "photo";
  /** which of the three rails on the Sidebar page the app is built on:
   *  full (AppSidebar, sections with sub-menus, collapse in the header),
   *  inset (ProjectSidebar, the page a surface card beside it) or
   *  edge (ProjectSidebar with a hairline edge, the page flat beside it) or
   *  topbar (the full rail without its user row, plus a TopBar above the page
   *  with search, theme, notifications and the account) */
  sidebar: "full" | "inset" | "edge" | "topbar";
  /** how that rail first opens: full collapses to an icon rail, inset and edge hide behind their trigger */
  sidebarState: "expanded" | "rail";
  /** charts and sparklines animate in (reduced-motion still wins) */
  motion: boolean;
};

export const FORMIC_CONFIG: FormicConfig = {
  avatar: "initials",
  sidebar: "full",
  sidebarState: "expanded",
  motion: true,
};
